### ISSUE TITLE
Thank you for this project

### ISSUE THREAD

**Issue by erickythierry** [Jakubscode/tcp-local-tunnel#17]
Thank you for this project. I was wanting to do something similar after trying to make FRP work with nodejs. I even managed it, but I can't have more granular control of the connections and exposed ports.
Fortunately, after a Google search I found this project which is exactly what I need. It saved me time that I would have wasted trying to do something on my own. 😂

### a question:
**Is there any way to control via code on the server which ports I expose (being able to undo the exposure or not according to some logic of my own)?**

I'm creating a scheme of several proxy servers that run on machines that are not directly accessible via the internet (they are behind a CGNAT), so I would use this project to tunnel their ports to a vps that would centralize everything. However, I would like to identify when these clients request a connection and then the server would provide a random port and store it somewhere so I can use it in other automations.
and if one of these clients stops working, the code would receive a notification that that tunnel was closed and so I could update the list of available proxies.

I believe I can do this using some extra logic with websocket connections just to identify whether a client is active or has been terminated. but I preferred to ask first if your project has this capability.

In any case, your code will be of great help.

**Comment by jayu** [comment]
Hey Ericky! Thanks for your interest!

Firstly a small disclaimer, this project is an old one and I'm not maintaining it. It has some issues with managing open connections, I don't recommend it for long running production usage. It was more like a PoC for me. Perhaps there are more robust solutions that achieve similar things. 

Regarding your question, there is not built in way to control the exposed ports dynamically from the app code. It's rather a simple script that expose those ports when started and stop working when killed. 

Feel free to take inspiration from the code, to build your own thing. But please be aware that Node.js network level implementation is considered as flaky and not easy to work with when it comes to robust production solutions. 
I experienced it myself when building this project, and later I found similar opinions in some articles online. 

I experienced problems with reliability of the open/close/error events when managing network connections, which is crucial for this project to work correctly. I worked on some old node version, I believe 8 or 10, so maybe things improved since then, but in general network layer reliability is a thing to keep your eye on when building similar network tunneling solutions. 

Cheers!

**Comment by erickythierry** [comment]
> Hey Ericky! Thanks for your interest!
> 
> Firstly a small disclaimer, this project is an old one and I'm not maintaining it. It has some issues with managing open connections, I don't recommend it for long running production usage. It was more like a PoC for me. Perhaps there are more robust solutions that achieve similar things.
> 
> Regarding your question, there is not built in way to control the exposed ports dynamically from the app code. It's rather a simple script that expose those ports when started and stop working when killed.
> 
> Feel free to take inspiration from the code, to build your own thing. But please be aware that Node.js network level implementation is considered as flaky and not easy to work with when it comes to robust production solutions. I experienced it myself when building this project, and later I found similar opinions in some articles online.
> 
> I experienced problems with reliability of the open/close/error events when managing network connections, which is crucial for this project to work correctly. I worked on some old node version, I believe 8 or 10, so maybe things improved since then, but in general network layer reliability is a thing to keep your eye on when building similar network tunneling solutions.
> 
> Cheers!

thanks for the tips.
My application description ended up looking like something robust but it's just a personal project too 😅
I did some tests and liked the performance.
I will make a fork and adapt it for my use.
🤜🤛
